# Generated by Django 5.2.5 on 2026-06-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportCardApp', '0002_alter_department_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AddField(
            model_name='student',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='result_published',
            field=models.BooleanField(default=False),
        ),
    ]
