# Generated by Django 5.2.5 on 2026-06-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReportCardApp', '0003_alter_student_options_student_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_name'], 'verbose_name': 'Student'},
        ),
    ]
